module.exports = licenseData = {
  state: undefined,
  family_name: undefined,
  given_name: undefined,
  gender: undefined,
  address: undefined,
  date_of_exp: undefined,
  date_of_birth: undefined,
  date_of_issue: undefined,
  weight: undefined,
  class: undefined,
  id: undefined,
  DD: undefined,
  document_type: "DRIVER LICENSE",
};
